name: .NET Core CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build library
      run: dotnet build DotNet.Safe/DotNet.Safe.csproj -f netstandard2.0
    - name: Build test project
      run: dotnet build DotNet.Safe.Test/DotNet.Safe.Test.csproj -f netcoreapp3.1
    - name: Run unit tests
      run: dotnet test DotNet.Safe.Test/DotNet.Safe.Test.csproj -f netcoreapp3.1
